# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        toolbar:
            toolbar: "toolbar"
            contentsCss:
                - '/css/styles.css'
    toolbars:
        configs:
            toolbar: [[
                "Maximize", "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-",
                "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "Indent", "Outdent", "-",
                "NumberedList", "BulletedList", "Link", "Unlink", "CodeSnippet"
            ]]
            extraPlugins:
                - 'Codesnippet'